# Generated by Django 4.2.1 on 2023-05-30 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0004_skills_alter_user_birthday'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skills',
            new_name='Skill',
        ),
    ]
